name: AWS-EC2 Instance CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          # AWS access key id
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS secret access key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Where EC2 instance is
          aws-region: ${{ secrets.AWS_REGION }}
          # AWS EC2 Instance id or ids
          instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
          # Command execution location
          # !!! The line below may vary depending on where your docker-compose file is located.
          working-directory: /home/ubuntu
          # Bash commands you want to execute
          command: |
            sudo docker-compose stop
            sudo docker-compose up --build
          # Comment for Send-Command
          comment: docker-compose.yml file re-pulls newer versions of book-portal images and runs them on the instance.
