name: Run Tests

on:
  push:
    branches:
      - [main, development]
  pull_request:
    branches:
      - [main, development]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'


      - name: Install Node packages
        working-directory: ./client
        run: npm install

      - name: Run tests
        working-directory: ./client
        run: npm test
